#### Import Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

In [ ]:
file_path = "user_interests_50_dataset.csv"  
df = pd.read_csv(file_path)

In [ ]:
location_mapping = pd.read_csv("location_mapping.csv")
nationality_mapping = pd.read_csv("nationality_mapping.csv")
language_mapping = pd.read_csv("language_mapping.csv")

In [4]:
location_dict = dict(zip(location_mapping["Location"], location_mapping["ID"]))
nationality_dict = dict(zip(nationality_mapping["Nationality"], nationality_mapping["ID"]))
language_dict = dict(zip(language_mapping["Language"], language_mapping["ID"]))

In [5]:
activity_columns = ["Basketball", "Yoga", "Hiking", "Cycling", "Gym", "Swimming", "Dancing", "Running", "Music", "Photography"]

In [6]:
df[activity_columns]

,Basketball,Yoga,Hiking,Cycling,Gym,Swimming,Dancing,Running,Music,Photography
0,5,1,3,2,3,5,1,1,2,5
1,1,4,4,4,4,1,5,3,5,3
2,5,5,1,2,3,2,5,3,2,2
3,3,1,3,1,4,5,1,4,4,2
4,1,2,4,1,2,1,5,4,1,3
5,5,4,5,4,2,5,1,1,4,5
6,3,1,2,5,4,5,2,2,3,5
7,1,2,4,1,3,4,3,1,1,1
8,1,5,2,5,1,2,4,3,3,5
9,3,4,4,1,3,1,1,2,3,4
10,5,5,5,3,2,1,2,1,1,1
11,3,4,3,4,3,1,2,4,4,5
12,5,1,2,1,3,1,4,1,3,2
13,3,4,5,4,5,1,5,4,2,5
14,4,2,4,1,3,5,1,2,5,2
15,4,5,3,5,1,4,1,3,2,5
16,3,4,3,3,5,4,4,4,2,5
17,5,5,5,1,3,1,2,3,2,5
18,2,1,3,1,5,1,4,1,1,3
19,5,5,3,4,3,5,3,3,3,1
20,4,2,3,2,3,1,5,4,4,2
21,2,2,2,2,4,2,1,2,3,2
22,2,2,1,5,1,4,1,4,5,3
23,2,5,1,2,1,1,4,3,5,3
24,1,5,3,4,1,2,3,1,5,2
25,3,3,4,4,2,4,4,5,2,2
26,4,3,5,1,1,3,4,1,1,2
27,2,1,3,3,3,2,1,5,3,3
28,1,1,3,2,5,3,1,4,2,3
29,2,3,3,2,3,4,2,2,1,5
30,3,3,2,4,2,1,4,1,5,5
31,3,4,2,2,2,1,4,1,5,1
32,1,4,5,1,2,5,5,4,3,2
33,4,3,2,2,2,5,1,2,4,1
34,5,5,5,5,4,5,4,5,2,5
35,2,5,2,3,5,3,5,4,2,4
36,4,5,3,4,3,1,4,5,1,1
37,4,4,2,5,4,4,5,5,3,5
38,4,5,2,2,5,5,5,2,1,4
39,4,2,4,3,3,3,4,5,5,4
40,3,4,1,1,4,3,4,4,2,2
41,3,3,3,2,2,2,5,5,4,4
42,3,4,3,3,1,5,1,4,4,5
43,3,2,3,2,3,3,1,3,2,4
44,2,4,4,1,4,2,1,3,3,3
45,5,1,3,1,4,4,4,2,2,2
46,1,4,5,1,1,1,2,1,3,5
47,2,3,2,3,4,4,2,4,5,4
48,1,1,4,2,5,1,5,3,5,5
49,2,1,2,5,1,1,2,2,5,3

In [7]:
min_value, max_value = 1, 5
df[activity_columns] = (df[activity_columns] - min_value) / (max_value - min_value)
df[activity_columns] = df[activity_columns].round(2)

In [8]:
df[activity_columns]

,Basketball,Yoga,Hiking,Cycling,Gym,Swimming,Dancing,Running,Music,Photography
0,1.00,0.00,0.50,0.25,0.50,1.00,0.00,0.00,0.25,1.00
1,0.00,0.75,0.75,0.75,0.75,0.00,1.00,0.50,1.00,0.50
2,1.00,1.00,0.00,0.25,0.50,0.25,1.00,0.50,0.25,0.25
3,0.50,0.00,0.50,0.00,0.75,1.00,0.00,0.75,0.75,0.25
4,0.00,0.25,0.75,0.00,0.25,0.00,1.00,0.75,0.00,0.50
5,1.00,0.75,1.00,0.75,0.25,1.00,0.00,0.00,0.75,1.00
6,0.50,0.00,0.25,1.00,0.75,1.00,0.25,0.25,0.50,1.00
7,0.00,0.25,0.75,0.00,0.50,0.75,0.50,0.00,0.00,0.00
8,0.00,1.00,0.25,1.00,0.00,0.25,0.75,0.50,0.50,1.00
9,0.50,0.75,0.75,0.00,0.50,0.00,0.00,0.25,0.50,0.75
10,1.00,1.00,1.00,0.50,0.25,0.00,0.25,0.00,0.00,0.00
11,0.50,0.75,0.50,0.75,0.50,0.00,0.25,0.75,0.75,1.00
12,1.00,0.00,0.25,0.00,0.50,0.00,0.75,0.00,0.50,0.25
13,0.50,0.75,1.00,0.75,1.00,0.00,1.00,0.75,0.25,1.00
14,0.75,0.25,0.75,0.00,0.50,1.00,0.00,0.25,1.00,0.25
15,0.75,1.00,0.50,1.00,0.00,0.75,0.00,0.50,0.25,1.00
16,0.50,0.75,0.50,0.50,1.00,0.75,0.75,0.75,0.25,1.00
17,1.00,1.00,1.00,0.00,0.50,0.00,0.25,0.50,0.25,1.00
18,0.25,0.00,0.50,0.00,1.00,0.00,0.75,0.00,0.00,0.50
19,1.00,1.00,0.50,0.75,0.50,1.00,0.50,0.50,0.50,0.00
20,0.75,0.25,0.50,0.25,0.50,0.00,1.00,0.75,0.75,0.25
21,0.25,0.25,0.25,0.25,0.75,0.25,0.00,0.25,0.50,0.25
22,0.25,0.25,0.00,1.00,0.00,0.75,0.00,0.75,1.00,0.50
23,0.25,1.00,0.00,0.25,0.00,0.00,0.75,0.50,1.00,0.50
24,0.00,1.00,0.50,0.75,0.00,0.25,0.50,0.00,1.00,0.25
25,0.50,0.50,0.75,0.75,0.25,0.75,0.75,1.00,0.25,0.25
26,0.75,0.50,1.00,0.00,0.00,0.50,0.75,0.00,0.00,0.25
27,0.25,0.00,0.50,0.50,0.50,0.25,0.00,1.00,0.50,0.50
28,0.00,0.00,0.50,0.25,1.00,0.50,0.00,0.75,0.25,0.50
29,0.25,0.50,0.50,0.25,0.50,0.75,0.25,0.25,0.00,1.00
30,0.50,0.50,0.25,0.75,0.25,0.00,0.75,0.00,1.00,1.00
31,0.50,0.75,0.25,0.25,0.25,0.00,0.75,0.00,1.00,0.00
32,0.00,0.75,1.00,0.00,0.25,1.00,1.00,0.75,0.50,0.25
33,0.75,0.50,0.25,0.25,0.25,1.00,0.00,0.25,0.75,0.00
34,1.00,1.00,1.00,1.00,0.75,1.00,0.75,1.00,0.25,1.00
35,0.25,1.00,0.25,0.50,1.00,0.50,1.00,0.75,0.25,0.75
36,0.75,1.00,0.50,0.75,0.50,0.00,0.75,1.00,0.00,0.00
37,0.75,0.75,0.25,1.00,0.75,0.75,1.00,1.00,0.50,1.00
38,0.75,1.00,0.25,0.25,1.00,1.00,1.00,0.25,0.00,0.75
39,0.75,0.25,0.75,0.50,0.50,0.50,0.75,1.00,1.00,0.75
40,0.50,0.75,0.00,0.00,0.75,0.50,0.75,0.75,0.25,0.25
41,0.50,0.50,0.50,0.25,0.25,0.25,1.00,1.00,0.75,0.75
42,0.50,0.75,0.50,0.50,0.00,1.00,0.00,0.75,0.75,1.00
43,0.50,0.25,0.50,0.25,0.50,0.50,0.00,0.50,0.25,0.75
44,0.25,0.75,0.75,0.00,0.75,0.25,0.00,0.50,0.50,0.50
45,1.00,0.00,0.50,0.00,0.75,0.75,0.75,0.25,0.25,0.25
46,0.00,0.75,1.00,0.00,0.00,0.00,0.25,0.00,0.50,1.00
47,0.25,0.50,0.25,0.50,0.75,0.75,0.25,0.75,1.00,0.75
48,0.00,0.00,0.75,0.25,1.00,0.00,1.00,0.50,1.00,1.00
49,0.25,0.00,0.25,1.00,0.00,0.00,0.25,0.25,1.00,0.50

In [9]:
user_score_min, user_score_max = 1, 10
df["User Score"] = (df["User Score"] - user_score_min) / (user_score_max - user_score_min)
df["User Score"] = df["User Score"].round(2)

In [10]:
days_of_week = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
df["Availability_Vector"] = df["Availability"].apply(lambda x: "[" + ", ".join(str(1 if day in x.split(", ") else 0) for day in days_of_week) + "]")
df.drop(columns=["Availability"], inplace=True)

In [11]:
gender_mapping = {"Male": 0, "Female": 1, "Other": 2, "Prefer not to say": 3}
df["Gender"] = df["Gender"].map(gender_mapping)

In [12]:
df["Location_ID"] = df["Location"].map(location_dict)
df["Nationality_ID"] = df["Nationality"].map(nationality_dict)

In [13]:
def map_languages(languages):
    if pd.isna(languages):
        return ""
    return [language_dict.get(lang.strip(), None) for lang in languages.split(",") if lang.strip() in language_dict]

df["Language_IDs"] = df["Languages Spoken"].apply(map_languages)

In [14]:
df.drop(columns=["Location", "Nationality", "Languages Spoken"], inplace=True)

In [15]:
df.to_csv("../Dataset/Pre_data/preprocessed_50user_data.csv", index=False)

In [16]:
print("✅ Preprocessing complete. Data saved as 'preprocessed_user_data.csv'.")

✅ Preprocessing complete. Data saved as 'preprocessed_user_data.csv'.